copyright = "© Ulrike Jozwiak"
defaultContentLanguage = "en"
disableKinds = ["taxonomy"]
enableRobotsTXT = true
languageCode = "de"
timeZone = "Europe/Berlin"
timeout = "120s"
title = "art-ist-in"

[params]
  defaultTheme = "dark"
  description = "Example site for hugo-theme-gallery"
  title = "My Gallery"
  bigPicture = "img/big-picture.jpg"
  [params.author]
    email = "user@example.com"
    name = "Ulrike Jozwiak"
  [params.socialIcons]
    facebook = "https://www.facebook.com/"
    instagram = "https://www.instagram.com/"
    youtube = "https://www.youtube.com/"
    email = "mailto:user@example.com"
    #website = "https://example.com"
    #mastodon = "https://example.com"
    #pixelfed = "https://example.com"
    #mixcloud = "https://example.com"
    #flickr = "https://www.flickr.com"
    #500px = "https://500px"
    #whatsapp = "1234567890"
  [params.gallery]
    #boxSpacing = 10
    #targetRowHeight = 288
    #targetRowHeightTolerance = 0.25

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML"]
  section = ["HTML"]

[imaging]
  quality = 75
  resampleFilter = "CatmullRom"
  [imaging.exif]
    disableDate = false
    disableLatLong = true
    includeFields = "ImageDescription|Orientation"

[module]
  [module.hugoVersion]
    min = "0.121.2"

[menu]
  [[menu.footer]]
    name = "MeinOrtMalerei"
    url = "https://art-ist-in.github.io/Meinortmalerei/"
    weight = 3
  [[menu.footer]]
    name = "ZiKiNos"
    url = "https://www.zikinos.de/"
    weight = 4

[services]
  [services.rss]
    limit = 100
